#!/bin/bash

# Boiler plate code to print context of this script
juju-log $JUJU_REMOTE_UNIT modified its settings
juju-log Relation settings:
relation-get
juju-log Relation members:
relation-list



# Relation properties


database=`relation-get database`
user=`relation-get user`
password=`relation-get password`
host=`relation-get private-address`

# Sanity checks
## If there is no database name defined, die
if [ -z "$database" ] ; then
    exit 0
fi




juju-log Config

cat <<EOF >> /srv/www/htdocs/config/database.yml
production:
  adapter: mysql2
  database: $database
  host: $host
  username: $user
  password: $password
  encoding: utf8

EOF


cd /srv/www/htdocs

source /usr/local/rvm/scripts/rvm

rake generate_secret_token
RAILS_ENV=production rake db:migrate
RAILS_ENV=production REDMINE_LANG=ru rake redmine:load_default_data

# least access permissions for the configuration file
#chown www-data:www-data $config_file_path
#chmod 0640 $config_file_path

juju-log "Opening port 80"
open-port 80/tcp
open-port 443/tcp
