#!/bin/bash

. inc/common

apt-get -y install --no-install-suggests --no-install-recommends  apache2 pwgen exim4-daemon-light libapache2-mod-passenger mysql-client build-essential libmysqlclient-dev

sed -i "s|dc_eximconfig_configtype='local'|dc_eximconfig_configtype='internet'|g" /etc/exim4/update-exim4.conf.conf

update-exim4.conf

a2dissite 000-default

apt-get  -y install ruby ruby-dev nodejs

gem install nokogiri
gem install rails -v 4.2
gem install bundler
gem install passenger
gem install mysql2

mkdir -p /srv/www/htdocs

curl -vv -L "http://www.redmine.org/releases/redmine-3.1.0.tar.gz" > /tmp/redmine.tar.gz
tar -C /srv/www/htdocs --strip-components=1 -zxf /tmp/redmine.tar.gz

cd /srv/www/htdocs/

bundle install --without development test postgresql sqlite rmagick

touch /srv/www/htdocs/config/database.yml

mkdir tmp tmp/pdf public/plugin_assets

install_path="/srv/www/htdocs/"

set_permissions
